# Generated by Django 4.2.6 on 2023-11-08 06:51

from django.db import migrations, models

import library_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("library_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(
                default="images/default.png", upload_to=library_app.models.upload_to
            ),
        ),
    ]
